### ISSUE TITLE
OAuth needed

### ISSUE THREAD

**Issue by apurv2** [apurv2/StudentAssistWebapp#1]
Oauth needed on both Java rest API side and JS side

**Comment by JBaba** [comment]
what tech we using at back-end ? spring yes ?

**Comment by apurv2** [comment]
Jax rs (restful) and JPA - hibernate

**Comment by JBaba** [comment]
It's jersey ?

**Comment by apurv2** [comment]
yes

**Comment by apurv2** [comment]
auth0.com

**Comment by apurv2** [comment]
@JBaba I will finish this.

**Comment by apurv2** [comment]
@NS123987  assigning it to you

**Comment by JBaba** [comment]
what was the conclusion ?

**Comment by apurv2** [comment]
we can use facebook token.
FB application Id is public
